UI/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UI.Models;

namespace UI.Controllers
{
    [Authorize]
    public class FeedbackController : Controller
    {
        private readonly IFeedbackRepositroy repository;

        public FeedbackController(IFeedbackRepositroy repository)
        {
            this.repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                repository.AddFeedback(feedback);

                return RedirectToAction("FeedbackComplete");
            }
            return View(feedback);

            
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }
    }
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width"/>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/content/site.css"/>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-controller="Home" asp-action="Index" class="navbar-brand">Bethany's Pie Shop</a>
                    </li>
                    <li>
                        <a asp-controller="Feedback" asp-action="Index">Feedback</a>
                    </li>
                    <partial name="_LoginPartial"/>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
    </div>
    @RenderSection("Scripts", required:false)
</body>
</html>